In [1]:
import numpy as np

In [ ]:
w = np.array([[0.1, 0.2, 0.3], 
              [0.4, 0.5, 0.6]])

A_diag = np.array([[0.1, 0.2, 0.3],
                    [0.4, 0.5, 0.6]])


J = 2
N = 3

In [12]:
w * A_diag

array([[0.01, 0.04, 0.09],
       [0.16, 0.25, 0.36]])

In [13]:
np.dot(w.T, A_diag)

array([[0.17, 0.22, 0.27],
       [0.22, 0.29, 0.36],
       [0.27, 0.36, 0.45]])

In [16]:
np.dot(w.T, A_diag) * w

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [18]:
np.dot(np.dot(w.T, A_diag), w)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [14]:
(w * (A_diag * w))

array([[0.001, 0.008, 0.027],
       [0.064, 0.125, 0.216]])

In [20]:
# sum of Ai * wi^2
(A_diag * w**2).sum()

0.44100000000000006

In [34]:
import torch
(A_diag * w.pow(2)).sum(dim=2)

AttributeError: 'numpy.ndarray' object has no attribute 'pow'

In [ ]:
import os, sys


def get_dir_n_levels_up(path, n):
    # Go up n levels from the given path
    for _ in range(n):
        path = os.path.dirname(path)
    return path


proj_root = get_dir_n_levels_up(os.path.abspath("__file__"), 3)
sys.path.append(proj_root)

from opinion_dynamics.models import OpinionNet

B, N, J = 2, 4, 3
model = OpinionNet(nr_agents=N, nr_betas=J)
model.train()

print(model.predict_A_b_c.weight.grad) 

x = torch.randn(B, N)
out = model(x)

loss = out["c"].sum()
loss.backward()

model.predict_A_b_c.weight.grad 

None


tensor([[0.0000, 0.1379, 0.3885,  ..., 0.1720, 0.0000, 0.3240],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]])